---
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
data:
  frontend-image: YmhhdmdhbmRoaS9teWV4dGVybmFsOnYy
  backend-image: YmhhdmdhbmRoaS9teWludGVybmFsOnYy
  PORT: ODA=
  SERVER: aHR0cDovL2RlbG9pdHRlLWRyaWZ0ZXJzLWJhY2tlbmQtc2VydmljZQ==